config/routes.rb
Rails.application.routes.draw do
  resources :targets, only: [:create, :show, :delete] do
    get :delete
  end

  root 'home#index'
  namespace :sessions do
    get 'weibo_create'
    get 'weibo_callback'
    get 'destroy'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/status.rb
class Status < ActiveRecord::Base

end

app/models/target.rb
class Target < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :target

  class << self
    def signup_with_weibo_token token
      User.find_or_create_by(wb_uid: token.params['uid']) do |u|
        u.wb_token = token.token
        u.wb_expires_in = token.expires_in
        u.wb_expires_at = token.expires_at
        u.wb_refresh_token = token.refresh_token
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @target = Target.new
    @target.user_id = session[:login_user_id]
    @current_user = User.find session[:login_user_id] if session[:login_user_id]
    if @current_user.present? && @current_user.target.present?
      @target = @current_user.target
      @statuses = Status.where(wb_uid: @current_user.target.wb_uid).order(posted_at: :desc).to_a
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def weibo_create
    redirect_to WeiboOAuth2::Client.new.authorize_url
  end

  def weibo_callback
    token = WeiboOAuth2::Client.new.auth_code.get_token(params[:code])
    session[:login_user_id] = User.signup_with_weibo_token(token).id
    redirect_to '/'
  end

  def destroy
    session[:login_user_id] = nil
    redirect_to '/'
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy, :delete]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
    @target.user_id = session[:login_user_id]
  end

  # GET /targets/1/edit
  def edit
  end

  # GET /targets/1/delete
  def delete
    if session[:login_user_id] != @target.user.id
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'You cannot delete this target.' }
      end
      return
    end
    @target.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Target was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # POST /targets
  # POST /targets.json
  def create
    login_user = User.find(session[:login_user_id])
    if login_user.target.present?
      return respond_to do |format|
        format.html { redirect_to login_user.target, notice: "你只能关注一个人，你已经关注了#{login_user.target.wb_uid}了" }
        format.json { render json: @target.errors, status: :bad_request }
      end
    end

    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id]||params[:target_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:wb_uid, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/home/_status.html.haml
- if status.present?
  %p
    = status['text']
    %br
    - status['pic_urls'].each do |pic_url|
      = image_tag pic_url['thumbnail_pic']
    - if status['retweeted_status']
      .retweet
        = render 'status', :status => status['retweeted_status']
    %p
      %small= status['created_at']
- else
  * 一条无效的微博, 找小狼投诉 *

app/views/home/index.html.haml
-if @current_user
  :plain
    <!--
  =@current_user.inspect
  :plain
    -->
  = link_to '登出', '/sessions/destroy'
  - if @current_user.target
    %div
      你已经关注了 #{link_to("http://weibo.com/u/#{@current_user.target.wb_uid}", "http://weibo.com/u/#{@current_user.target.wb_uid}", :target => '_blank')}
      |
      = link_to '取消关注', target_path(@target)
    %hr
    %div
      - @statuses.each do |status|
        .weibo
          = render 'status', :status => status.raw
  - else
    %div
      %p
        输入你要关注的微博 ID（个人页的 http://weibo.com/u/1644773785 地址后面这串数字）
    %div
      -#=form_tag('/targets/create') do
      -#  =text_field_tag 'wb_uid'
      -#  =submit_tag '确认无误，提交'
      = render 'targets/form'
-else
  =link_to image_tag('http://www.sinaimg.cn/blog/developer/wiki/48.png'), '/sessions/weibo_create'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    :plain
      <meta property="wb:webmaster" content="5b14b26a7f0690ac" />
    %title ABWeibo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/targets/_form.html.haml
= form_for @target do |f|
  - if @target.errors.any?
    #error_explanation
      %h2= "#{pluralize(@target.errors.count, "error")} prohibited this target from being saved:"
      %ul
        - @target.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :wb_uid, '微博 ID'
    = f.text_field :wb_uid
    = f.hidden_field :user_id
  .actions
    = f.submit '确认无误，提交'

app/views/targets/edit.html.haml
%h1 Editing target

= render 'form'

= link_to 'Show', @target
\|
= link_to 'Back', targets_path

app/views/targets/index.html.haml
%h1 Listing targets

%table
  %thead
    %tr
      %th Wb uid
      %th
      %th
      %th

  %tbody
    - @targets.each do |target|
      %tr
        %td= target.wb_uid
        %td= link_to 'Show', target
        %td= link_to 'Edit', edit_target_path(target)
        %td= link_to 'Destroy', target, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Target', new_target_path

app/views/targets/new.html.haml
%h1 New target

= render 'form'

= link_to 'Back', targets_path

app/views/targets/show.html.haml
%p#notice= notice

%p
  %b 微博 ID:
  = @target.wb_uid
  %b 已被加入队列，如果第一次关注，会在点击返回后一分钟左右后完成第一次数据抓取

-#= link_to 'Edit', edit_target_path(@target)
= link_to '返回', root_path

%hr
= link_to '取消关注', target_delete_path(@target)